name: Cloud App CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  ci-cd-workflow:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Environments
        uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Authenticate Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Authenticate GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build temporary image for scanning
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: scout-target:scan
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/cloud-cache:latest

      - name: Run CVE Vulnerability Scan
        uses: docker/scout-action@v1
        with:
          command: cves
          image: scout-target:scan
          only-severities: high,critical
          exit-code: true

      - name: Build and Push Multi-Architecture Image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.sha }}
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/cloud-cache:latest
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/cloud-cache:latest,mode=max